image: docker:20.10.7

stages:
  - build

entries build:
  stage: build
  image: docker:20.10.7
  services:
    - docker:20.10.7-dind
  variables:
    DOCKER_DRIVER: overlay2
    IMAGE_TAG: '$CI_REGISTRY_IMAGE/entries:$CI_COMMIT_REF_SLUG'
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $IMAGE_TAG -f ./Accounting.Service.Entries/Dockerfile .
    - docker push $IMAGE_TAG 
